config/routes.rb
Rails.application.routes.draw do

  get 'printers/index'

  root 'home#index'

  # Devise
  devise_for :users, :skip => [:registrations]

  # Home
  get '/', to: 'home#index'

  # Departments
  resources :departments, except: :show

  # Printers
  resources :printers, except: :show

  # Cartridges
  resources :cartridges, except: :show

  # Users
  resources :users, except: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartridge.rb
class Cartridge < ApplicationRecord
  enum kind: [:original, :recharged]

  validates_presence_of :name, :kind

  def name_with_kind
    "#{name} - #{kind}"
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :printers
  validates_presence_of :name
end

app/models/printer.rb
class Printer < ApplicationRecord
  belongs_to :department

  enum kind: [:laser, :inkjet]
  enum status: [:active, :inactive]

  validates_presence_of :name, :ip_address, :status, :kind
end

app/models/user.rb
class User < ApplicationRecord
  # Enums
  enum role: [:full_access, :restricted_access]

  # Scopes
  scope :with_full_access, -> { where(role: :full_access)}
  scope :with_restricted_access, -> { where(role: :restricted_access)}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Pundit
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Authenticate with devise
  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception

  # Set layout
  layout :layout_by_resource

  private

  # Pundit rescue
  def user_not_authorized
    flash[:alert] = t('messages.denied')
    redirect_to(request.referrer || root_path)
  end

  # Layout per resource_name
  def layout_by_resource
    if devise_controller? && resource_name == :user && action_name == 'new'
      "devise"
    else
      "application"
    end
  end
end

app/controllers/cartridges_controller.rb
class CartridgesController < ApplicationController
  before_action :set_cartridge, only: [:edit, :update, :destroy]

  def index
    @cartridges = Cartridge.all.order(:name)
  end

  def new
    @cartridge = Cartridge.new
  end

  def create
    @cartridge = Cartridge.new(params_cartridge)
    if @cartridge.save
      redirect_to cartridges_path, notice: "O cartucho #{@cartridge.name} foi criado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cartridge.update(params_cartridge)
      redirect_to cartridges_path, notice: "O cartucho #{@cartridge.name} foi atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    cartridge_name = @cartridge.name
    if @cartridge.destroy
      redirect_to cartridges_path, notice: "O cartucho #{cartridge_name} foi excluído com sucesso!"
    else
      render :index
    end
  end

  private

  def set_cartridge
    @cartridge = Cartridge.find(params[:id])
  end

  def params_cartridge
    params.require(:cartridge).permit(:name, :kind)
  end
end

app/controllers/cartridges_controller/cartridge_service.rb
class CartridgesController::CartridgeService
  attr_accessor :cartridge

  def self.create(params_cartridge)
    @cartridge = Department.new(params_cartridge)

    if @cartridge.valid?
      @cartridge.save!
    end

    @cartridge
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:edit, :update]

  def index
    @departments = Department.all.order(:name)
  end

  def new
    @department = Department.new
  end

  def create
    @department = DepartmentService.create(params_department)
    unless @department.errors.any?
      redirect_to departments_path, notice: "O departamento #{@department.name} foi criado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @department.update(params_department)
      redirect_to departments_path, notice: "O departamento #{@department.name} foi atualizado com sucesso!"
    else
      render :edit
    end
  end

  private

  def set_department
    @department = Department.find(params[:id])
  end

  def params_department
    params.require(:department).permit(:name)
  end
end

app/controllers/departments_controller/department_service.rb
class DepartmentsController::DepartmentService
  attr_accessor :department

  def self.create(params_department)
    @department = Department.new(params_department)

    if @department.valid?
      @department.save!
    end

    @department
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController
  before_action :set_printer, only: [:edit, :update]
  before_action :set_options_for_select, only: [:new, :edit, :create]

  def index
    @printers = Printer.all.order(:name)
  end

  def new
    @printer = Printer.new
  end

  def create
    @printer = PrinterService.create(params_printer)
    unless @printer.errors.any?
      redirect_to printers_path, notice: "A impressora #{@printer.name} foi criado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @printer.update(params_printer)
      redirect_to printers_path, notice: "A impressora #{@printer.name} foi atualizado com sucesso!"
    else
      render :edit
    end
  end

  private

  def set_options_for_select
    @department_options_for_select = Department.all
  end

  def set_printer
    @printer = Printer.find(params[:id])
  end

  def params_printer
    params.require(:printer).permit(:name, :kind, :ip_address, :department_id, :leased, :status)
  end
end

app/controllers/printers_controller/printer_service.rb
class PrintersController::PrinterService
  attr_accessor :printer

  def self.create(params_printer)
    @printer = Printer.new(params_printer)

    if @printer.valid?
      @printer.save!
    end

    @printer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: :new
  after_action :verify_policy_scoped, only: :index

  def index
    @users = policy_scope(User)
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(params_user)
    if @user.save
      redirect_to users_path, notice: "O usuario #{@user.name} foi criado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    remove_password_if_not_present

    if @user.update(params_user)
      redirect_to users_path, notice: "O usuario #{@user.name} foi atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    user_name = @user.name
    if @user.destroy
      redirect_to users_path, notice: "O usuario #{user_name} foi excluído com sucesso!"
    else
      render :index
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def params_user
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def remove_password_if_not_present
    passwd = params[:password]
    passwd_confirmation = params[:password_confirmation]

    if passwd.blank? && passwd_confirmation.blank?
      params[:user].except!(:password, :password_confirmation)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartridges_helper.rb
module CartridgesHelper
OptionsForKinds = Struct.new(:id, :name)
  def cartridge_options_for_kinds
    Cartridge.kinds_i18n.map do | key, value |
      OptionsForKinds.new(key, value)
    end
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/printers_helper.rb
module PrintersHelper
  OptionsForKinds = Struct.new(:id, :name)
  OptionsForStatus = Struct.new(:id, :name)

  def options_for_kinds
    Printer.kinds_i18n.map do | key, value |
      OptionsForKinds.new(key, value)
    end
  end

  def options_for_status
    Printer.statuses_i18n.map do | key, value |
      OptionsForStatus.new(key, value)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cartridges/_form.html.erb
<h1 class="page-header">Cartuchos</h1>

<% if @cartridge.errors.any? %>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <ul>
    <% @cartridge.errors.full_messages.each do |message| %>
    <li> <%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= action %>
  </div>
  <div class="panel-body">
    <div class="col-lg-6">
      <%= form_for @cartridge do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "Ex: HP 60" %>
        </div>

        <div class="form-group">
          <%= f.label :kind %>
          <%= f.collection_radio_buttons(:kind, cartridge_options_for_kinds, :id, :name) do |b| %>
            <div class="radio">
              <%= b.label { b.radio_button + b.text } %>
            </div>
          <% end %>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
      <% end %>
    </div>
  </div>
</div>

app/views/cartridges/edit.html.erb
<%= render partial: "cartridges/form", locals: { action: "Editando cartucho"} %>

app/views/cartridges/index.html.erb
<h1 class="page-header"><%= @cartridges.model_name.human(count: 2)%></h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('messages.listing', model: @cartridges.model_name.human(count: 2)) %>
    <%= link_to new_cartridge_path, class: "btn btn-success btn-circle pull-right",
        style: "margin-top: -5px" do %>
      <i class="fa fa-plus"></i>
    <% end %>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th><%= @cartridges.model.human_attribute_name('name') %></th>
            <th>Tipo</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <% count = 0 %>
          <% @cartridges.each do |cartridge| %>
            <tr>
              <td> <%= count += 1 %> </td>
              <td> <%= cartridge.name %> </td>
              <td> <%= cartridge.kind_i18n %></td>
              <td style="width: 150px">
                <%= link_to edit_cartridge_path(cartridge), class: "btn btn-primary btn-circle" do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <button type="button" disabled="disabled" class="btn btn-danger btn-circle">
                  <i class="fa fa-minus"></i>
                </button>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/cartridges/new.html.erb
<%= render partial: "cartridges/form", locals: { action: "Novo cartucho"} %>

app/views/departments/_form.html.erb
<h1 class="page-header">Departamentos</h1>

<% if @department.errors.any? %>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <ul>
    <% @department.errors.full_messages.each do |message| %>
    <li> <%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= action %>
  </div>
  <div class="panel-body">
    <div class="col-lg-6">
      <%= form_for @department do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "Ex: Informática" %>

        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
      <% end %>
    </div>
  </div>
</div>

app/views/departments/edit.html.erb
<%= render partial: "departments/form", locals: { action: "Editando departamento"} %>

app/views/departments/index.html.erb
<h1 class="page-header">Departamentos</h1>

<div class="panel panel-default">
  <div class="panel-heading">
    Listando departamentos
    <%= link_to new_department_path, class: "btn btn-success btn-circle pull-right",
        style: "margin-top: -5px" do %>
      <i class="fa fa-plus"></i>
    <% end %>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Nome</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <% count = 0 %>
          <% @departments.each do |department| %>
            <tr>
              <td> <%= count += 1 %> </td>
              <td> <%= department.name %> </td>
              <td style="width: 150px">
                <%= link_to edit_department_path(department), class: "btn btn-primary btn-circle" do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <button type="button" disabled="disabled" class="btn btn-danger btn-circle">
                  <i class="fa fa-minus"></i>
                </button>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/departments/new.html.erb
<%= render partial: "departments/form", locals: { action: "Novo departamento"} %>

app/views/home/index.html.erb
<h1 class="page-header">Dashboard</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>One Admin</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>

</head>

<body>
  <div id="wrapper">
    <%= render partial: "shared/navigation" %>
    <div id="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render partial: "shared/notifications" %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> One Admin </title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'devise', media: 'all'%>

  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/printers/_form.html.erb
<h1 class="page-header"><%= @printer.model_name.human(count: 2) %></h1>

<% if @printer.errors.any? %>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <ul>
    <% @printer.errors.full_messages.each do |message| %>
    <li> <%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= action %>
  </div>
  <div class="panel-body">
    <div class="col-lg-6">
      <%= form_for @printer do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "Ex: HP 8600" %>
        </div>
        <div class="form-group">
          <%= f.label :department %>
          <%= f.collection_select(:department_id, @department_options_for_select, :id, :name,
                {include_blank: "Selecione uma opção"}, {class: "form-control"}) %>
        </div>
        <div class="form-group">
          <%= f.label :kind %>
          <%= f.collection_select(:kind, options_for_kinds, :id, :name,
              {include_blank: "Selecione uma opção"}, {class: "form-control"}) %>
        </div>
        <div class="form-group">
          <%= f.label :status %>
          <%= f.collection_radio_buttons(:status, options_for_status, :id, :name) do |b| %>
            <div class="radio">
              <%= b.label { b.radio_button + b.text } %>
            </div>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :ip_address %>
          <%= f.text_field :ip_address, class: "form-control", placeholder: "Ex: 10.80.20.50" %>
        </div>
        <div class="form-group">
          <%= f.check_box :leased, class: "checkbox-inline" %>
          <%= f.label :leased %>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
      <% end %>
    </div>
  </div>
</div>

app/views/printers/edit.html.erb
<%= render partial: "printers/form", locals: { action: "Editando impressora"} %>

app/views/printers/index.html.erb
<h1 class="page-header"><%= @printers.model_name.human(count: 2) %></h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('messages.listing', model: @printers.model_name.human(count: 2)) %>
    <%= link_to new_printer_path, class: "btn btn-success btn-circle pull-right",
        style: "margin-top: -5px" do %>
      <i class="fa fa-plus"></i>
    <% end %>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Nome</th>
            <th>Departamento</th>
            <th>Tipo</th>
            <th>IP</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <% count = 0 %>
          <% @printers.each do |printer| %>
            <tr>
              <td> <%= count += 1 %> </td>
              <td> <%= printer.name %> </td>
              <td> <%= printer.department.name %></td>
              <td> <%= printer.kind_i18n %></td>
              <td> <%= printer.ip_address %></td>
              <td style="width: 150px">
                <%= link_to edit_printer_path(printer), class: "btn btn-primary btn-circle" do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <button type="button" disabled="disabled" class="btn btn-danger btn-circle">
                  <i class="fa fa-minus"></i>
                </button>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/printers/new.html.erb
<%= render partial: "printers/form", locals: { action: "Nova impressora"} %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="index.html">One Admin</a>
  </div>

  <ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <%= current_user.email %>
        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <!-- <li class="divider"></li> -->
        <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa fa-sign-out fa-fw"></i> Sair</a>
        <% end %>
      </li>
    </ul>
  </li>
</ul>

<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <li>
        <%= link_to root_path do %>
          <i class="fa fa-dashboard fa-fw"></i> Dashboard
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
        <i class="fa fa-file-text-o fa-fw"></i> Impressão
        <span class="fa arrow"></span>
        <% end %>
        <ul class="nav nav-second-level collapse">
          <li>
            <%= link_to printers_path do %>
            <i class="fa fa-print fa-fw"></i> Impressoras
            <% end %>
          </li>
          <li>
            <%= link_to cartridges_path do %>
            <i class="fa fa-circle fa-fw"></i> Cartuchos
            <% end %>
          </li>
        </ul>
        <li>
          <%= link_to users_path do %>
          <i class="fa fa-users fa-fw"></i> Usuários
          <% end %>
        </li>
        <li>
          <%= link_to departments_path do %>
          <i class="fa fa-building-o fa-fw"></i> Departamentos
          <% end %>
        </li>
      </li>
    </ul>
  </div>
</div>
</nav>

app/views/shared/_notifications.html.erb
<% if notice %>
  <script type="text/javascript">
    $.notify("<%= notice %>", { globalPosition: "top center", className: 'success' });
  </script>
<% end %>

<% if alert %>
  <script type="text/javascript">
    $.notify("<%= alert %>", { globalPosition: "top center", className: 'error' });
  </script>
<% end %>

app/views/users/_form.html.erb
<h1 class="page-header">Usuario</h1>

<% if @user.errors.any? %>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li> <%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= action %>
  </div>
  <div class="panel-body">
    <div class="col-lg-6">
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "Ex: João da Silva"%>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control", placeholder: "Ex: joão@email.com"%>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control", placeholder: "Mínimo de 6 caracteres"%>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Repita a senha"%>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render partial: "users/form", locals: { action: "Editando Usuario"} %>

app/views/users/index.html.erb
<h1 class="page-header"><%= @users.model_name.human(count: 2) %></h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('messages.listing', model: @users.model_name.human(count: 2)) %>

    <% if policy(@users).new? %>
      <%= link_to new_user_path, class: "btn btn-success btn-circle pull-right",
      style: "margin-top: -5px" do %>
      <i class="fa fa-plus"></i>
      <% end %>
      <% else %>
      <%= link_to '#', class: "btn btn-success btn-circle pull-right",
      style: "margin-top: -5px", disabled: "disabled" do %>
      <i class="fa fa-plus"></i>
      <% end %>
    <% end %>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th><%= @users.model.human_attribute_name('name') %></th>
            <th><%= @users.model.human_attribute_name('email')%></th>
            <th><%= @users.model.human_attribute_name('role')%></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% count = 0 %>
          <% @users.each do |user| %>
            <tr>
              <td> <%= count += 1 %> </td>
              <td> <%= user.name %>  </td>
              <td> <%= user.email %> </td>
              <td> <%= user.role_i18n  %> </td>
              <td style="width: 150px">
                <%= link_to edit_user_path(user), class: "btn btn-primary btn-circle" do %>
                  <i class="fa fa-edit"></i>
                <% end %>

                <% if current_user.id != user.id %>
                  <%= link_to user_path(user), class: "btn btn-danger btn-circle",
                  method: :delete, data: {confirm: t('messages.confirm_with', item: user.name)} do %>
                    <i class="fa fa-minus"></i>
                  <% end %>
                <% else %>
                  <%= link_to '#', class: "btn btn-danger btn-circle", disabled: "disabled" do %>
                    <i class="fa fa-minus"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render partial: "users/form", locals: { action: "Novo Usuario"} %>